# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master", "gl_support" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.9", "3.10", "3.11"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Docker info
      run: |
        docker info

    - name: Build image
      run: |
        docker build -t mediapipe-conda .

    - name: Build package
      run: |
        docker run \
          -e PY_VERSION \
          -e HOST_USER_ID=$(id -u) \
          -v ${PWD}:/mediapipe \
          mediapipe-conda bash /mediapipe/.script/build_step.sh
      env:
        PY_VERSION: ${{ matrix.python-version }}

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact ${{ matrix.python-version }}
        path: dist/mediapipe*.whl

